services:
  - type: web
    name: satellite-app
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300 --workers 1 --threads 2
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
